package edu.ncsu.csc.itrust2.models.persistent;

/**
 * This class is the object that holds the data needed to be stored in an access
 * log.
 *
 * @author cmharri5
 */
public class AccessLogData {

    private String accessor;     // = userLog.get( 0 ).getPrimaryUser();
    private String accessorRole; // =
                                 // Role.ROLE_PATIENT.getLanding().split(
                                 // "," )[0];
    private String dateandtime;  // = userLog.get( 0
                                 // ).getTime().toString();
    private String transType;    // =
                                 // TransactionType.ACCOUNT_LOCKOUT_EMAIL_SENT.getDescription();

    /**
     * Empty constructor of Access Log
     */
    public AccessLogData () {
        // empty constructor
        setAccessor( "" );
        setAccessorRole( "" );
        setDateandtime( "" );
        setTransType( "" );
    }

    /**
     * This creates an AccessLogData object with the following parameters.
     *
     * @param accessor
     *            username of the accessor
     * @param accessorRole
     *            role of the accessor
     * @param dateandtime
     *            data and time of access
     * @param transType
     *            transaction type
     */
    public AccessLogData ( final String accessor, final String accessorRole, final String dateandtime,
            final String transType ) {
        setAccessor( accessor );
        setAccessorRole( accessorRole );
        setDateandtime( dateandtime );
        setTransType( transType );
    }

    /**
     * This gets the accessor's username
     *
     * @return accessor
     */
    public String getAccessor () {
        return accessor;
    }

    /**
     * This sets the accessor's username
     *
     * @param accessor
     *            accessor's username
     */
    public void setAccessor ( final String accessor ) {
        this.accessor = accessor;
    }

    /**
     * This gets the accessor's role
     *
     * @return accessor's role
     */
    public String getAccessorRole () {
        return accessorRole;
    }

    /**
     * This sets the accessor's role
     *
     * @param accessorRole
     *            accessor's role
     */
    public void setAccessorRole ( final String accessorRole ) {
        this.accessorRole = accessorRole;
    }

    /**
     * This gets the date an time as a string
     *
     * @return date and time
     */
    public String getDateandtime () {
        return dateandtime;
    }

    /**
     * This sets the date and time when given a string
     *
     * @param dateandtime
     *            string representation of a date and time
     */
    public void setDateandtime ( final String dateandtime ) {
        this.dateandtime = dateandtime;
    }

    /**
     * This gets the transaction type as a string
     *
     * @return transaction type
     */
    public String getTransType () {
        return transType;
    }

    /**
     * This sets the transaction type as a string
     *
     * @param transType
     *            string representation of transaction type
     */
    public void setTransType ( final String transType ) {
        this.transType = transType;
    }

    /**
     * This is the autogenerated hashcode method
     *
     * @return hashed value
     */
    @Override
    public int hashCode () {
        final int prime = 31;
        int result = 1;
        result = prime * result + ( ( accessor == null ) ? 0 : accessor.hashCode() );
        result = prime * result + ( ( accessorRole == null ) ? 0 : accessorRole.hashCode() );
        result = prime * result + ( ( dateandtime == null ) ? 0 : dateandtime.hashCode() );
        result = prime * result + ( ( transType == null ) ? 0 : transType.hashCode() );
        return result;
    }

    /**
     * This tests if two access log data objects are equal
     * 
     * @param obj
     *            the object to compare this to
     * @return true if objects are equal and false otherwise
     */
    @Override
    public boolean equals ( final Object obj ) {
        if ( this == obj ) {
            return true;
        }
        if ( obj == null ) {
            return false;
        }
        if ( getClass() != obj.getClass() ) {
            return false;
        }
        final AccessLogData other = (AccessLogData) obj;
        if ( accessor == null ) {
            if ( other.accessor != null ) {
                return false;
            }
        }
        else if ( !accessor.equals( other.accessor ) ) {
            return false;
        }
        if ( accessorRole == null ) {
            if ( other.accessorRole != null ) {
                return false;
            }
        }
        else if ( !accessorRole.equals( other.accessorRole ) ) {
            return false;
        }
        if ( dateandtime == null ) {
            if ( other.dateandtime != null ) {
                return false;
            }
        }
        else if ( !dateandtime.equals( other.dateandtime ) ) {
            return false;
        }
        if ( transType == null ) {
            if ( other.transType != null ) {
                return false;
            }
        }
        else if ( !transType.equals( other.transType ) ) {
            return false;
        }
        return true;
    }

}
